manifest:
    api_version: v1
    run_id: 2026-01-13_23-48-57
    profile:
        path: profiles/batch_mixing_tank.yaml
        distribution: inline
    network:
        data_plane:
            server_listen_ip: 192.168.10.99
            target_ip: 192.168.10.99
            target_port: 44818
    roles:
        server:
            agent: ssh://tturner@192.168.100.25?key=/Users/tturner/.ssh/id_ed25519_cipdip&os=darwin&elevate=true
            mode: emulator
            personality: adapter
        client:
            agent: ssh://tony@sentinel24.com@192.168.100.15?key=/Users/tturner/.ssh/id_ed25519_cipdip&os=windows&elevate=true
            scenario: dpi_explicit
            duration_seconds: 60
            interval_ms: 100
    readiness:
        method: structured_stdout
        timeout_seconds: 30
    artifacts:
        bundle_format: dir
resolved_at: "2026-01-13T23:48:58Z"
profile_path: /Users/tturner/Documents/GitHub/cipdip/profiles/batch_mixing_tank.yaml
profile_checksum: sha256:64be0091483f6888ddb8532f4fff4699bb9250b6f2fe303edf370dc25e7e9187
profile_content: |
    metadata:
      name: "Batch Mixing Tank"
      description: "Phase-driven batch process"
      version: "1.0"
      seed: 67890
      personality: logix_like

    data_model:
      tags:
        # Phase tracking
        - name: Phase
          type: INT
          initial_value: 0
          writable: false
          update_rule: latch

        - name: PhaseName
          type: INT
          initial_value: 0
          writable: false
          update_rule: latch

        # Process values
        - name: TankLevel
          type: REAL
          initial_value: 0.0
          writable: false
          update_rule: ramp
          update_params:
            min: 0.0
            max: 100.0
            rate: 2.0

        - name: Temperature
          type: REAL
          initial_value: 20.0
          writable: false
          update_rule: ramp
          update_params:
            min: 20.0
            max: 85.0
            rate: 0.5

        - name: Pressure
          type: REAL
          initial_value: 14.7
          writable: false
          update_rule: sine
          update_params:
            amplitude: 2.0
            offset: 15.0
            period: 30s

        # Actuators
        - name: MixerSpeed
          type: INT
          initial_value: 0
          writable: true
          update_rule: static

        - name: HeaterEnable
          type: BOOL
          initial_value: false
          writable: false
          update_rule: latch

        - name: FillValve
          type: BOOL
          initial_value: false
          writable: false
          update_rule: latch

        - name: DrainValve
          type: BOOL
          initial_value: false
          writable: false
          update_rule: latch

        - name: AgitatorOn
          type: BOOL
          initial_value: false
          writable: false
          update_rule: latch

        # Recipe and control
        - name: RecipeID
          type: INT
          initial_value: 0
          writable: true
          update_rule: static

        - name: BatchStart
          type: BOOL
          initial_value: false
          writable: true
          update_rule: static

        - name: BatchComplete
          type: BOOL
          initial_value: false
          writable: false
          update_rule: latch

        - name: BatchAbort
          type: BOOL
          initial_value: false
          writable: true
          update_rule: static

        # Setpoints
        - name: TempSetpoint
          type: REAL
          initial_value: 65.0
          writable: true
          update_rule: static

        - name: FillLevel
          type: REAL
          initial_value: 80.0
          writable: true
          update_rule: static

        - name: MixTime
          type: INT
          initial_value: 45
          writable: true
          update_rule: static

        - name: HoldTime
          type: INT
          initial_value: 30
          writable: true
          update_rule: static

        # Alarms
        - name: TempHighAlarm
          type: BOOL
          initial_value: false
          writable: false
          update_rule: latch

        - name: LevelHighAlarm
          type: BOOL
          initial_value: false
          writable: false
          update_rule: latch

        # Counters
        - name: BatchCount
          type: DINT
          initial_value: 1547
          writable: false
          update_rule: counter
          update_params:
            increment: 1
            interval: 600s

    state_machine:
      initial_state: idle
      states:
        idle:
          description: "Waiting for batch start"
          duration: 20s
          transitions:
            - to: fill
              condition: "tag:BatchStart==true"
              priority: 1
          tag_overrides:
            Phase: "static:0"
            BatchComplete: "static:false"
            FillValve: "static:false"
            DrainValve: "static:false"
            HeaterEnable: "static:false"
            AgitatorOn: "static:false"

        fill:
          description: "Filling tank to target level"
          duration: 30s
          transitions:
            - to: mix
              condition: "tag:TankLevel>=80"
              priority: 1
            - to: idle
              condition: "tag:BatchAbort==true"
              priority: 2
          tag_overrides:
            Phase: "static:1"
            FillValve: "static:true"
            TankLevel: "ramp:0:100:2"

        mix:
          description: "Mixing contents"
          duration: 45s
          transitions:
            - to: heat
              condition: "timer:45s"
              priority: 1
            - to: idle
              condition: "tag:BatchAbort==true"
              priority: 2
          tag_overrides:
            Phase: "static:2"
            FillValve: "static:false"
            AgitatorOn: "static:true"
            MixerSpeed: "static:100"

        heat:
          description: "Heating to setpoint"
          duration: 60s
          transitions:
            - to: hold
              condition: "tag:Temperature>=65"
              priority: 1
            - to: idle
              condition: "tag:BatchAbort==true"
              priority: 2
          tag_overrides:
            Phase: "static:3"
            HeaterEnable: "static:true"
            Temperature: "ramp:20:80:0.5"

        hold:
          description: "Holding at temperature"
          duration: 30s
          transitions:
            - to: drain
              condition: "timer:30s"
              priority: 1
            - to: idle
              condition: "tag:BatchAbort==true"
              priority: 2
          tag_overrides:
            Phase: "static:4"

        drain:
          description: "Draining tank"
          duration: 40s
          transitions:
            - to: cip
              condition: "tag:TankLevel<=5"
              priority: 1
          tag_overrides:
            Phase: "static:5"
            DrainValve: "static:true"
            HeaterEnable: "static:false"
            AgitatorOn: "static:false"
            MixerSpeed: "static:0"
            TankLevel: "ramp:100:0:2.5"

        cip:
          description: "Clean-in-place cycle"
          duration: 60s
          transitions:
            - to: idle
              condition: "timer:60s"
              priority: 1
          tag_overrides:
            Phase: "static:6"
            DrainValve: "static:false"
            BatchComplete: "static:true"
            BatchStart: "static:false"
          events:
            - name: cip_valve_cycle
              trigger: "timer:10s"
              actions:
                - type: log
                  value: "CIP valve cycling"
            - name: cip_complete
              trigger: "timer:55s"
              actions:
                - type: log
                  value: "CIP cycle complete"

    roles:
      hmi:
        description: "Operator HMI - monitors batch progress, starts batches"
        poll_interval: 500ms
        batch_size: 12
        read_tags:
          - Phase
          - TankLevel
          - Temperature
          - Pressure
          - MixerSpeed
          - HeaterEnable
          - FillValve
          - DrainValve
          - RecipeID
          - BatchComplete
          - TempSetpoint
          - TempHighAlarm
        write_tags:
          - RecipeID
          - BatchStart
          - BatchAbort
          - MixerSpeed
          - TempSetpoint
          - FillLevel
          - MixTime
          - HoldTime
        write_events:
          - trigger: "state:idle"
            tag: RecipeID
            value: "random:1:5"
            condition: "once"
          - trigger: "state:idle"
            tag: BatchStart
            value: true
            condition: "timer:10s"
          - trigger: "state:mix"
            tag: MixerSpeed
            value: "random:80:120"

      historian:
        description: "Batch historian - captures all process data"
        poll_interval: 2s
        batch_size: 18
        read_tags:
          - Phase
          - TankLevel
          - Temperature
          - Pressure
          - MixerSpeed
          - HeaterEnable
          - FillValve
          - DrainValve
          - AgitatorOn
          - RecipeID
          - BatchComplete
          - TempSetpoint
          - FillLevel
          - BatchCount
          - TempHighAlarm
          - LevelHighAlarm
        write_tags: []

      ews:
        description: "Engineering workstation - recipe development"
        poll_interval: 1s
        batch_size: 10
        read_tags:
          - Phase
          - TankLevel
          - Temperature
          - Pressure
          - RecipeID
          - BatchComplete
          - TempSetpoint
          - MixTime
          - HoldTime
        write_tags:
          - TempSetpoint
          - FillLevel
          - MixTime
          - HoldTime
        write_events:
          - trigger: "state:idle"
            tag: TempSetpoint
            value: "random:55:75"
          - trigger: "state:idle"
            tag: FillLevel
            value: "random:70:90"

    baselining:
      required_states:
        - idle
        - fill
        - mix
        - heat
        - hold
        - drain
        - cip
      min_time_per_state: 20s
      required_events:
        - cip_valve_cycle
        - cip_complete
      total_duration: 15m
      export_pcap: true
      export_summaries: true

    torture:
      latency_spikes:
        probability: 0.03
        min_delay: 50ms
        max_delay: 300ms
      burst_amplify: 1.5
      timing_jitter: 30ms
server_args:
    - server
    - --listen-ip
    - 192.168.10.99
    - --listen-port
    - "44818"
    - --personality
    - adapter
    - --tui-stats
client_args:
    - client
    - --ip
    - 192.168.10.99
    - --port
    - "44818"
    - --scenario
    - dpi_explicit
    - --duration-seconds
    - "60"
    - --interval-ms
    - "100"
    - --tui-stats
tool_version: dev
controller_os: darwin
controller_arch: arm64
