version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*bufio.Writer).Flush
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
