version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      exclude-functions:
        # File/IO cleanup
        - (*os.File).Close
        - (*os.File).Write
        - (*os.File).Sync
        - (io.Closer).Close
        - os.Remove
        - os.RemoveAll
        - os.WriteFile
        # Buffered writers
        - (*bufio.Writer).Flush
        - (*text/tabwriter.Writer).Flush
        # Formatting / console output
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - fmt.Sscanf
        # Network cleanup / best-effort
        - (net.Conn).Close
        - (net.Conn).SetReadDeadline
        - (net.Conn).SetWriteDeadline

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
